"""LASE Sprint-5 training driver.

Trains the Language-Adversarial Speaker Encoder (models/novel/lase.py) on
same-speaker cross-language pairs generated by ``data/codeswitch_gen.py``.

**Not** yet wired to Modal. This file is a local-runnable scaffold so the
training loop is reviewable before GPU spend. A Modal wrapper will follow
once the loss curves converge on a CPU smoke.

Usage (CPU smoke, 10 steps, 2 clips)::

    uv run python -m training.lase_train \\
        --manifest data/codeswitch_pairs/manifest.jsonl \\
        --max-steps 10 --batch-size 2 --device cpu

Usage (A100, real training)::

    uv run python -m training.lase_train \\
        --manifest data/codeswitch_pairs/manifest.jsonl \\
        --max-steps 4000 --batch-size 32 --device cuda \\
        --output-dir /data/lase/round_1 --grl-peak 0.2

**Loss recipe.**

- ``L_speaker``: supervised contrastive (SupCon) over voice_id. Two clips
  of the same voice should pull together in embedding space; two clips of
  different voices should push apart. Language-agnostic by construction
  because batch composition mixes languages.
- ``L_lang_adv``: cross-entropy of a 4-way language classifier (en/hi/te/ta)
  on the GRL-output of the same embedding. With gradient reversal, making
  this loss LOW actively teaches the encoder to HIDE language information.

- Total loss: ``L = L_speaker + lambda_t * L_lang_adv`` with λ scheduled
  via ``models/novel/lase.py::lambda_schedule`` (0 at warmup, ramps to
  ``grl_peak`` over ``mid`` steps, holds).

**Invariants.**

- Backbone (pretrained speaker encoder) stays frozen for R1; only the
  projection MLP and the language head train.
- Batches must contain at least one same-voice pair AND at least two
  languages or SupCon collapses to trivial (zero contrast).
- Grad-clip at 1.0; reports NaN → hard abort (LR too high, drop 5×).
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


@dataclass
class TrainConfig:
    manifest: Path
    output_dir: Path
    device: str = "cuda"
    batch_size: int = 32
    max_steps: int = 4_000
    learning_rate: float = 1e-4
    grl_peak: float = 0.2
    grl_warmup_steps: int = 200
    grl_ramp_steps: int = 1_000
    save_every: int = 500
    log_every: int = 25
    grad_clip: float = 1.0
    supcon_temperature: float = 0.07
    backbone: str = "wavlm"

    @classmethod
    def from_args(cls, argv: list[str] | None = None) -> "TrainConfig":
        p = argparse.ArgumentParser(description="LASE Sprint-5 training driver")
        p.add_argument("--manifest", required=True, type=Path,
                       help="Path to codeswitch-pairs manifest.jsonl")
        p.add_argument("--output-dir", default=Path("./lase_run"), type=Path)
        p.add_argument("--device", default="cuda", choices=["cpu", "cuda", "mps"])
        p.add_argument("--batch-size", type=int, default=32)
        p.add_argument("--max-steps", type=int, default=4_000)
        p.add_argument("--backbone", default="wavlm", choices=["wavlm", "dummy"],
                       help="Speaker-encoder backbone. wavlm = WavLM-base-plus (real); dummy = stub for shape tests.")
        p.add_argument("--learning-rate", type=float, default=1e-4)
        p.add_argument("--grl-peak", type=float, default=0.2)
        p.add_argument("--grl-warmup-steps", type=int, default=200)
        p.add_argument("--grl-ramp-steps", type=int, default=1_000)
        p.add_argument("--save-every", type=int, default=500)
        p.add_argument("--log-every", type=int, default=25)
        p.add_argument("--grad-clip", type=float, default=1.0)
        p.add_argument("--supcon-temperature", type=float, default=0.07)
        args = p.parse_args(argv)
        return cls(**vars(args))


def _load_manifest(path: Path) -> list[dict]:
    """Load the codeswitch-pairs manifest (one JSON line per clip)."""
    if not path.exists():
        raise FileNotFoundError(
            f"manifest not found at {path}. Run `python -m data.codeswitch_gen` first."
        )
    rows: list[dict] = []
    with path.open() as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            rows.append(json.loads(line))
    if not rows:
        raise ValueError(f"manifest {path} is empty")
    required = {"voice_id", "lang", "wav_path"}
    missing = required - set(rows[0].keys())
    if missing:
        raise ValueError(f"manifest row missing required keys: {missing}")
    return rows


def _batch_iter(rows: list[dict], batch_size: int) -> Iterable[list[dict]]:
    """Minimal deterministic batcher. Round-robins through voices so each
    batch contains ≥2 voices (keeps SupCon non-trivial)."""
    import random
    random.seed(0)
    voices = sorted({r["voice_id"] for r in rows})
    by_voice = {v: [r for r in rows if r["voice_id"] == v] for v in voices}
    while True:
        batch: list[dict] = []
        voice_cycle = voices.copy()
        random.shuffle(voice_cycle)
        for v in voice_cycle:
            if len(batch) >= batch_size:
                break
            candidates = by_voice[v]
            if len(candidates) >= 2:
                batch.extend(random.sample(candidates, 2))
        if len(batch) < batch_size:
            # Pad with random singles if voices run out
            batch.extend(random.sample(rows, batch_size - len(batch)))
        yield batch[:batch_size]


def train(cfg: TrainConfig) -> None:
    """Main loop. Lazy imports so `--help` works without torch installed."""
    import torch  # noqa: PLC0415
    from models.novel.lase import (  # noqa: PLC0415
        DummySpeakerEncoder,
        LambdaSchedule,
        LASE,
        WavLMSpeakerEncoder,
        supcon_loss,
    )

    device = torch.device(cfg.device if torch.cuda.is_available() or cfg.device != "cuda" else "cpu")
    rows = _load_manifest(cfg.manifest)
    print(f"[lase_train] loaded {len(rows)} clips from {cfg.manifest}", flush=True)

    # R1 wiring (2026-05-01): real WavLM-base-plus backbone. Frozen for R1;
    # only the projection MLP + GRL classifier head train. Set --backbone dummy
    # to fall back to DummySpeakerEncoder for shape-only smoke tests.
    embedding_dim = 256
    backbone_choice = getattr(cfg, "backbone", "wavlm")
    if backbone_choice == "dummy":
        backbone = DummySpeakerEncoder(embedding_dim=embedding_dim)
        print("[lase_train] backbone=DummySpeakerEncoder (shape-only smoke)", flush=True)
    else:
        backbone = WavLMSpeakerEncoder(
            model_name="microsoft/wavlm-base-plus",
            embedding_dim=embedding_dim,
            freeze_backbone=True,
        )
        print(f"[lase_train] backbone=WavLMSpeakerEncoder (frozen R1)", flush=True)
    schedule = LambdaSchedule(
        warmup_steps=cfg.grl_warmup_steps,
        ramp_steps=cfg.grl_ramp_steps,
        peak=cfg.grl_peak,
    )
    model = LASE(
        backbone=backbone,
        embedding_dim=embedding_dim,
        n_languages=4,
        lambda_schedule=schedule,
    ).to(device)
    optimizer = torch.optim.AdamW(
        (p for p in model.parameters() if p.requires_grad),
        lr=cfg.learning_rate, weight_decay=0.01,
    )
    ce_loss = torch.nn.CrossEntropyLoss()

    lang_to_idx = {"en": 0, "hi": 1, "te": 2, "ta": 3}
    cfg.output_dir.mkdir(parents=True, exist_ok=True)

    for step, batch in zip(range(1, cfg.max_steps + 1), _batch_iter(rows, cfg.batch_size)):
        # Embed batch. Two paths:
        #   (a) If a sibling `.pt` exists for each wav (pre-embedded by
        #       codeswitch_gen --extract-embeddings), load directly. Fast.
        #   (b) Else fall back to raw audio → backbone. Requires torchaudio
        #       and a real backbone to be useful; DummySpeakerEncoder just
        #       pools to scalar.
        wav_stems = [Path(r["wav_path"]).with_suffix(".pt") for r in batch]
        if all(p.exists() for p in wav_stems):
            # Skip the backbone entirely — we already have embeddings.
            x = torch.stack([torch.load(p, map_location=device) for p in wav_stems])
            embeddings = x
            # Run the GRL + classifier only (no backbone forward).
            reversed_ = model.grl(embeddings)
            lang_logits = model.lang_classifier(reversed_)
            out = {"embedding": embeddings, "lang_logits": lang_logits}
        else:
            import torchaudio  # noqa: PLC0415
            waves: list[torch.Tensor] = []
            for r in batch:
                wav, sr = torchaudio.load(r["wav_path"])
                if sr != 16_000:
                    wav = torchaudio.functional.resample(wav, sr, 16_000)
                # Crop / pad to 2s
                wav = wav[0][:32_000]
                if wav.shape[0] < 32_000:
                    wav = torch.nn.functional.pad(wav, (0, 32_000 - wav.shape[0]))
                waves.append(wav)
            x = torch.stack(waves).to(device)
            out = model(x)

        voice_ids = torch.tensor(
            [hash(r["voice_id"]) % (2 ** 31) for r in batch],
            device=device, dtype=torch.long,
        )
        lang_labels = torch.tensor(
            [lang_to_idx.get(r["lang"], 0) for r in batch],
            device=device, dtype=torch.long,
        )
        model.set_step(step)
        lambda_t = model.current_lambda

        l_speaker = supcon_loss(out["embedding"], voice_ids, temperature=cfg.supcon_temperature)
        l_lang_adv = ce_loss(out["lang_logits"], lang_labels)
        l_total = l_speaker + lambda_t * l_lang_adv

        if not torch.isfinite(l_total):
            raise RuntimeError(
                f"non-finite loss at step {step}: L_speaker={l_speaker.item():.4f} "
                f"L_lang_adv={l_lang_adv.item():.4f} lambda={lambda_t:.4f}. "
                "Abort — LR too high, drop 5× and restart."
            )

        optimizer.zero_grad(set_to_none=True)
        l_total.backward()
        torch.nn.utils.clip_grad_norm_(
            (p for p in model.parameters() if p.requires_grad),
            cfg.grad_clip,
        )
        optimizer.step()

        if step % cfg.log_every == 0:
            print(
                f"[step {step:5d}] L_total={l_total.item():.4f} "
                f"L_speaker={l_speaker.item():.4f} L_lang_adv={l_lang_adv.item():.4f} "
                f"lambda={lambda_t:.3f}",
                flush=True,
            )
        if step % cfg.save_every == 0:
            ckpt = cfg.output_dir / f"step_{step}.pt"
            torch.save({"model": model.state_dict(), "step": step, "config": cfg.__dict__}, ckpt)
            print(f"[checkpoint] {ckpt}", flush=True)

    final = cfg.output_dir / "last.pt"
    torch.save({"model": model.state_dict(), "step": cfg.max_steps, "config": cfg.__dict__}, final)
    print(f"[done] final checkpoint at {final}", flush=True)


if __name__ == "__main__":
    train(TrainConfig.from_args(sys.argv[1:]))
